[{ "id": 1, "name": "Rapheal Javascript Library", "url": "js/lib/raphael.min.js", "per": 5, "type": "jsonp" },
{ "id": 2, "name": "China Map Resource", "url": "js/res/chinaMapConfig.min.js", "per": 2, "type": "jsonp" },
{ "id": 3, "name": "jQuery Map Extension", "url": "js/map.min.js", "per": 2, "type": "jsonp" },
{ "id": 4, "name": "Map of Sixteen data file", "url": "js/data.js", "per": 2, "type": "jsonp" },
{ "id": 5, "name": "Map of Sixteen JS file", "url": "js/main.min.js", "per": 5, "type": "jsonp" },
{ "id": 6, "name": "Map of Sixteen CSS file", "url": "style/style.min.css", "per": 5, "type": "css" },
{ "id": 7, "name": "City Picture Group", "url": "img/cityGroup.v2.jpg", "per": 10, "type": "img" },
{ "id": 32, "name": "Default background - 1", "url": "img/background/1.jpg", "per": 1, "type": "img" },
{ "id": 33, "name": "Default background - 2", "url": "img/background/2.jpg", "per": 1, "type": "img" },
{ "id": 34, "name": "Default background - 3", "url": "img/background/3.jpg", "per": 1, "type": "img" },
{ "id": 35, "name": "Default background - 4", "url": "img/background/4.jpg", "per": 1, "type": "img" },
{ "id": 36, "name": "Default background - 5", "url": "img/background/5.jpg", "per": 1, "type": "img" },
{ "id": 37, "name": "Default background - 6", "url": "img/background/6.jpg", "per": 1, "type": "img" },
{ "id": 38, "name": "Default background - 7", "url": "img/background/7.jpg", "per": 1, "type": "img" },
{ "id": 39, "name": "Default background - 8", "url": "img/background/8.jpg", "per": 1, "type": "img" },
{ "id": 40, "name": "Default background - 9", "url": "img/background/9.jpg", "per": 1, "type": "img" },
{ "id": 71, "name": "Picture of background - 1", "url": "person/img/1.jpg", "per": 2, "type": "img" },
{ "id": 72, "name": "Picture of background - 2", "url": "person/img/2.jpg", "per": 2, "type": "img" },
{ "id": 73, "name": "Picture of background - 5", "url": "person/img/5.jpg", "per": 2, "type": "img" },
{ "id": 74, "name": "Picture of background - 6 - v2", "url": "person/img/6.v2.jpg", "per": 2, "type": "img" },
{ "id": 75, "name": "Picture of background - 7", "url": "person/img/7.jpg", "per": 2, "type": "img" },
{ "id": 76, "name": "Picture of background - 8", "url": "person/img/8.jpg", "per": 2, "type": "img" },
{ "id": 77, "name": "Picture of background - 9", "url": "person/img/9.jpg", "per": 2, "type": "img" },
{ "id": 78, "name": "Picture of background - 10", "url": "person/img/10.jpg", "per": 2, "type": "img" },
{ "id": 78, "name": "Picture of background - 11", "url": "person/img/11.jpg", "per": 2, "type": "img" },
{ "id": 78, "name": "Picture of background - 12", "url": "person/img/12.jpg", "per": 2, "type": "img" },
{ "id": 79, "name": "Photo Group", "url": "img/photoGroup.jpg", "per": 10, "type": "img" }]
