<?php
// This File Contains Application Cache Configuration
//TODO: Update this file.
//Set Header
header("Content-type:text/cache-manifest");
?>
CACHE MANIFEST
#app-version 1.0.3###
CACHE:
    /favicon.ico
    /style/style.min.css
    /img/icon.jpg
    /img/cityGroup.v2.jpg
    /img/welcome/welcome-1.png
    /img/welcome/welcome-2.png
    /img/welcome/welcome-3.png
    /img/welcome/welcome-4.png
    /img/background/1.jpg
    /img/background/2.jpg
    /img/background/3.jpg
    /img/background/4.jpg
    /img/background/5.jpg
    /img/background/6.jpg
    /img/background/7.jpg
    /img/background/8.jpg
    /img/background/9.jpg
    /person/img/1.jpg
    /person/img/2.jpg
    /person/img/5.jpg
    /person/img/6.v2.jpg
    /person/img/7.jpg
    /person/img/8.jpg
    /person/img/9.jpg
    /person/img/10.jpg
    /person/img/11.jpg
    /person/img/12.jpg
    /person/page/1.html
    /person/page/2.html
    /person/page/3.html
    /person/page/4.html
    /person/page/5.html
    /person/page/6.html
    /person/page/7.html
    /person/page/8.html
    /person/page/9.html
    /person/page/11.html
    /person/page/12.html
    /img/photoGroup.v2.jpg
    /js/loaderList.js
    /js/lib/raphael.min.js
    /js/lib/jquery-2.1.1.min.js
    /js/lib/jquery.mobile.custom.min.js
    /js/res/chinaMapConfig.min.js
    /js/map.min.js
    /js/data.min.js
    /js/main.min.js
NETWORK:
    /src.php
    /js/loader.js.php